### PR TITLE
statically link cdg plugin

### PR DESCRIPTION
**Pull request by gdesmott**

### CODE REVIEW

**Comment by gdesmott** [comment]
@sdroege : I'm trying to statically link the cdg plugin into my application to make it easier for users. But I'm hitting this error. Any idea what I'm doing wrong here?

```
error[E0432]: unresolved import `gst_plugin_cdg`
  --> src/main.rs:15:5
   |
15 | use gst_plugin_cdg as gstcdg;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `gst_plugin_cdg` external crate
```

**Comment by sdroege** [comment]
`extern crate gst_plugin_cdg as gstcdg;` is needed in `main.rs` or `lib.rs`. Or you rename it in the `Cargo.toml` directly.

**Comment by gdesmott** [comment]
I tried that (not needed with rust 2018) but it can't find it either:

```
error[E0463]: can't find crate for `gst_plugin_cdg`
  --> src/main.rs:15:1
   |
15 | extern crate gst_plugin_cdg;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by sdroege** [comment]
> not needed with rust 2018

It's needed with 2018 if you want to rename, unless you rename in `Cargo.toml`.

But that should work exactly like that :) Can you retry?

**Comment by gdesmott** [comment]
I mean even without renaming it doesn't work. I updated the patch.

```
error[E0432]: unresolved import `gst_plugin_cdg`
  --> src/main.rs:15:5
   |
15 | use gst_plugin_cdg;
   |     ^^^^^^^^^^^^^^ no `gst_plugin_cdg` external crate
```

**Comment by gdesmott** [comment]
oh, so the lib name override the package name then! Good to know, thanks!

**Pull request merged**
